[
    {
        "_id": "Final",
        "count": 7,
        "statusChanges": [
            {
                "_id": "64933a7d883a61d55e0b9477",
                "eip": "5007",
                "fromStatus": "Last Call",
                "toStatus": "Final",
                "title": "Time NFT, ERC-721 Time Extension",
                "status": "Final",
                "author": "Anders (@0xanders), Lance (@LanceSnow), Shrug <shrug@emojidao.org>",
                "created": "2022-04-12T18:30:00.000Z",
                "changeDate": "2023-05-28T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/eip-5007-eip-721-time-extension/8924",
                "deadline": "undefined",
                "requires": "165, 721",
                "changedDay": 29,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 4,
                "createdYear": 2022,
                "__v": 0
            },
            {
                "_id": "64933ae5883a61d55e0b965e",
                "eip": "5507",
                "fromStatus": "Last Call",
                "toStatus": "Final",
                "title": "Refundable Tokens",
                "status": "Final",
                "author": "elie222 (@elie222), Gavin John (@Pandapip1)",
                "created": "2022-08-18T18:30:00.000Z",
                "changeDate": "2023-05-14T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/eip-5507-refundable-nfts/10451",
                "deadline": "undefined",
                "requires": "20, 165, 721, 1155",
                "changedDay": 15,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 8,
                "createdYear": 2022,
                "__v": 0
            },
            {
                "_id": "64933afb883a61d55e0b96c2",
                "eip": "5570",
                "fromStatus": "Last Call",
                "toStatus": "Final",
                "title": "Digital Receipt Non-Fungible Tokens",
                "status": "Final",
                "author": "Sean Darcy (@darcys22)",
                "created": "2022-08-31T18:30:00.000Z",
                "changeDate": "2023-05-28T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/idea-standard-digital-receipts-using-erc-721/9908",
                "deadline": "undefined",
                "requires": "721",
                "changedDay": 29,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 9,
                "createdYear": 2022,
                "__v": 0
            },
            {
                "_id": "64933b07883a61d55e0b96fc",
                "eip": "5615",
                "fromStatus": "Last Call",
                "toStatus": "Final",
                "title": "ERC-1155 Supply Extension",
                "status": "Final",
                "author": "Gavin John (@Pandapip1)",
                "created": "2023-05-24T18:30:00.000Z",
                "changeDate": "2023-05-14T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/eip-5615-eip-1155-supply-extension/10732",
                "deadline": "undefined",
                "requires": "1155",
                "changedDay": 15,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 5,
                "createdYear": 2023,
                "__v": 0
            },
            {
                "_id": "64933b5b883a61d55e0b9877",
                "eip": "6105",
                "fromStatus": "Last Call",
                "toStatus": "Final",
                "title": "No Intermediary NFT Trading Protocol",
                "status": "Final",
                "author": "5660-eth (@5660-eth), Silvere Heraudeau (@lambdalf-dev), Martin McConnell (@offgridgecko), Abu <team10kuni@gmail.com>, Wizard Wang",
                "created": "2022-12-01T18:30:00.000Z",
                "changeDate": "2023-05-14T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/eip6105-no-intermediary-nft-trading-protocol/12171",
                "deadline": "undefined",
                "requires": "20, 165, 721, 2981",
                "changedDay": 15,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 12,
                "createdYear": 2022,
                "__v": 0
            },
            {
                "_id": "64933ba3883a61d55e0b999f",
                "eip": "6454",
                "fromStatus": "Last Call",
                "toStatus": "Final",
                "title": "Minimal Transferable NFT detection interface",
                "status": "Final",
                "author": "Bruno Škvorc (@Swader), Francesco Sullo (@sullof), Steven Pineda (@steven2308), Stevan Bogosavljevic (@stevyhacker), Jan Turk (@ThunderDeliverer)",
                "created": "2023-01-30T18:30:00.000Z",
                "changeDate": "2023-05-28T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/minimalistic-transferable-interface/12517",
                "deadline": "undefined",
                "requires": "165, 721",
                "changedDay": 29,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 1,
                "createdYear": 2023,
                "__v": 0
            },
            {
                "_id": "64933bc9883a61d55e0b9a42",
                "eip": "6672",
                "fromStatus": "Last Call",
                "toStatus": "Final",
                "title": "Multi-redeemable NFTs",
                "status": "Final",
                "author": "RE:DREAMER Lab <dev@redreamer.io>, Archie Chang (@ArchieR7) <archie@redreamer.io>, Kai Yu (@chihkaiyu) <kai@redreamer.io>, Yonathan Randyanto (@Randyanto) <randy@redreamer.io>, Boyu Chu (@chuboyu) <boyu@redreamer.io>",
                "created": "2023-02-20T18:30:00.000Z",
                "changeDate": "2023-05-14T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/eip-6672-multi-redeemable-nfts/13276",
                "deadline": "undefined",
                "requires": "165, 721",
                "changedDay": 15,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 2,
                "createdYear": 2023,
                "__v": 0
            }
        ]
    },
    {
        "_id": "Last Call",
        "count": 6,
        "statusChanges": [
            {
                "_id": "64933a80883a61d55e0b9487",
                "eip": "5008",
                "fromStatus": "Review",
                "toStatus": "Last Call",
                "title": "ERC-721 Nonce Extension",
                "status": "Last Call",
                "author": "Anders (@0xanders), Lance (@LanceSnow), Shrug <shrug@emojidao.org>",
                "created": "2022-04-09T18:30:00.000Z",
                "changeDate": "2023-05-10T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/eip5008-eip-721-nonce-and-metadata-update-extension/8925",
                "deadline": "2023-06-01",
                "requires": "165, 721",
                "changedDay": 11,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 4,
                "createdYear": 2022,
                "__v": 0
            },
            {
                "_id": "64933aa2883a61d55e0b9527",
                "eip": "5169",
                "fromStatus": "Review",
                "toStatus": "Last Call",
                "title": "Client Script URI for Token Contracts",
                "status": "Last Call",
                "author": "James (@JamesSmartCell), Weiwu (@weiwu-zhang)",
                "created": "2022-05-02T18:30:00.000Z",
                "changeDate": "2023-05-02T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/eip-5169-client-script-uri-for-token-contracts/9674",
                "deadline": "2023-05-12",
                "requires": "20, 165, 721, 777, 1155",
                "changedDay": 3,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 5,
                "createdYear": 2022,
                "__v": 0
            },
            {
                "_id": "64933aac883a61d55e0b9557",
                "eip": "5202",
                "fromStatus": "Review",
                "toStatus": "Last Call",
                "title": "Blueprint contract format",
                "status": "Last Call",
                "author": "Charles Cooper (@charles-cooper), Edward Amor (@skellet0r)",
                "created": "2022-06-22T18:30:00.000Z",
                "changeDate": "2023-05-17T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/erc-5202-standard-factory-contract-format/9851",
                "deadline": "2023-06-01",
                "requires": "170",
                "changedDay": 18,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 6,
                "createdYear": 2022,
                "__v": 0
            },
            {
                "_id": "64933afb883a61d55e0b96c5",
                "eip": "5570",
                "fromStatus": "Review",
                "toStatus": "Last Call",
                "title": "Digital Receipt Non-Fungible Tokens",
                "status": "Last Call",
                "author": "Sean Darcy (@darcys22)",
                "created": "2022-08-31T18:30:00.000Z",
                "changeDate": "2023-04-30T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/idea-standard-digital-receipts-using-erc-721/9908",
                "deadline": "2023-05-16",
                "requires": "721",
                "changedDay": 1,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 9,
                "createdYear": 2022,
                "__v": 0
            },
            {
                "_id": "64933ba3883a61d55e0b99a2",
                "eip": "6454",
                "fromStatus": "Last Call",
                "toStatus": "Last Call",
                "title": "Minimal Transferable NFT detection interface",
                "status": "Last Call",
                "author": "Bruno Škvorc (@Swader), Francesco Sullo (@sullof), Steven Pineda (@steven2308), Stevan Bogosavljevic (@stevyhacker), Jan Turk (@ThunderDeliverer)",
                "created": "2023-01-30T18:30:00.000Z",
                "changeDate": "2023-05-16T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/minimalistic-transferable-interface/12517",
                "deadline": "2023-05-27",
                "requires": "165, 721",
                "changedDay": 17,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 1,
                "createdYear": 2023,
                "__v": 0
            },
            {
                "_id": "64933bc9883a61d55e0b9a45",
                "eip": "6672",
                "fromStatus": "Review",
                "toStatus": "Last Call",
                "title": "Multi-redeemable NFTs",
                "status": "Last Call",
                "author": "RE:DREAMER Lab <dev@redreamer.io>, Archie Chang (@ArchieR7) <archie@redreamer.io>, Kai Yu (@chihkaiyu) <kai@redreamer.io>, Yonathan Randyanto (@Randyanto) <randy@redreamer.io>",
                "created": "2023-02-20T18:30:00.000Z",
                "changeDate": "2023-04-30T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/eip-6672-multi-redeemable-nfts/13276",
                "deadline": "2023-05-16",
                "requires": "165, 721",
                "changedDay": 1,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 2,
                "createdYear": 2023,
                "__v": 0
            }
        ]
    },
    {
        "_id": "Review",
        "count": 6,
        "statusChanges": [
            {
                "_id": "64933693883a61d55e0b83f2",
                "eip": "1185",
                "fromStatus": "Draft",
                "toStatus": "Review",
                "title": "Storage of DNS Records in ENS",
                "status": "Review",
                "author": "Jim McDonald (@mcdee)",
                "created": "2018-06-25T18:30:00.000Z",
                "changeDate": "2023-05-30T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/eip1185-dns-resolver-profile-for-ens/1589",
                "deadline": "undefined",
                "requires": "137",
                "changedDay": 31,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 6,
                "createdYear": 2018,
                "__v": 0
            },
            {
                "_id": "649337c5883a61d55e0b88e0",
                "eip": "2015",
                "fromStatus": "Stagnant",
                "toStatus": "Review",
                "title": "Wallet Update Ethereum Chain RPC Method (`wallet_updateEthereumChain`)",
                "status": "Review",
                "author": "Pedro Gomes (@pedrouid), Erik Marks (@rekmarks)",
                "created": "2019-05-11T18:30:00.000Z",
                "changeDate": "2023-05-14T18:30:00.000Z",
                "type": "Standards Track",
                "category": "Interface",
                "discussion": "https://ethereum-magicians.org/t/eip-2015-wallet-update-chain-json-rpc-method-wallet-updatechain/3274",
                "deadline": "undefined",
                "requires": "155",
                "changedDay": 15,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 5,
                "createdYear": 2019,
                "__v": 0
            },
            {
                "_id": "64933b51883a61d55e0b984c",
                "eip": "6065",
                "fromStatus": "Draft",
                "toStatus": "Review",
                "title": "Real Estate Token",
                "status": "Review",
                "author": "Alex (@Alex-Klasma), Ben Fusek (@bfusek), Daniel Fallon-Cyr (@dfalloncyr)",
                "created": "2022-11-28T18:30:00.000Z",
                "changeDate": "2023-05-18T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/updated-eip-6065-real-estate-token/11936",
                "deadline": "undefined",
                "requires": "721",
                "changedDay": 19,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 11,
                "createdYear": 2022,
                "__v": 0
            },
            {
                "_id": "64933b5f883a61d55e0b988b",
                "eip": "6122",
                "fromStatus": "Draft",
                "toStatus": "Review",
                "title": "Forkid checks based on timestamps",
                "status": "Review",
                "author": "Marius van der Wijden (@MariusVanDerWijden)",
                "created": "2022-12-12T18:30:00.000Z",
                "changeDate": "2023-05-28T18:30:00.000Z",
                "type": "Standards Track",
                "category": "Networking",
                "discussion": "https://ethereum-magicians.org/t/eip-6122-forkid-checks-based-on-timestamps/12130",
                "deadline": "undefined",
                "requires": "2124",
                "changedDay": 29,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 12,
                "createdYear": 2022,
                "__v": 0
            },
            {
                "_id": "64933bd1883a61d55e0b9a6b",
                "eip": "6808",
                "fromStatus": "Draft",
                "toStatus": "Review",
                "title": "Fungible Key Bound Token",
                "status": "Review",
                "author": "Mihai Onila (@MihaiORO), Nick Zeman (@NickZCZ), Narcis Cotaie (@NarcisCRO)",
                "created": "2023-03-30T18:30:00.000Z",
                "changeDate": "2023-05-28T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/fungible-key-bound-token-kbt/13624",
                "deadline": "undefined",
                "requires": "20",
                "changedDay": 29,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 3,
                "createdYear": 2023,
                "__v": 0
            },
            {
                "_id": "64933bd3883a61d55e0b9a72",
                "eip": "6809",
                "fromStatus": "Draft",
                "toStatus": "Review",
                "title": "Non-Fungible Key Bound Token",
                "status": "Review",
                "author": "Mihai Onila (@MihaiORO), Nick Zeman (@NickZCZ), Narcis Cotaie (@NarcisCRO)",
                "created": "2023-03-30T18:30:00.000Z",
                "changeDate": "2023-05-28T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/non-fungible-key-bound-token-kbt/13625",
                "deadline": "undefined",
                "requires": "721",
                "changedDay": 29,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 3,
                "createdYear": 2023,
                "__v": 0
            }
        ]
    },
    {
        "_id": "Draft",
        "count": 20,
        "statusChanges": [
            {
                "_id": "64933af6883a61d55e0b96ab",
                "eip": "5564",
                "fromStatus": "unknown",
                "toStatus": "Draft",
                "title": "Stealth Addresses",
                "status": "Draft",
                "author": "Toni Wahrstätter (@nerolation), Matt Solomon (@mds1), Ben DiFrancesco (@apbendi), Vitalik Buterin (@vbuterin)",
                "created": "2022-08-12T18:30:00.000Z",
                "changeDate": "2023-05-02T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/eip-5566-stealth-addresses-for-smart-contract-wallets/10614",
                "deadline": "undefined",
                "requires": "undefined",
                "changedDay": 3,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 8,
                "createdYear": 2022,
                "__v": 0
            },
            {
                "_id": "64933b50883a61d55e0b9848",
                "eip": "6065",
                "fromStatus": "unknown",
                "toStatus": "Draft",
                "title": "Real Estate Token",
                "status": "Draft",
                "author": "Alex (@Alex-Klasma), Ben Fusek (@bfusek), Daniel Fallon-Cyr (@dfalloncyr)",
                "created": "2022-11-28T18:30:00.000Z",
                "changeDate": "2023-04-30T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/updated-eip-6065-real-estate-token/11936",
                "deadline": "undefined",
                "requires": "721",
                "changedDay": 1,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 11,
                "createdYear": 2022,
                "__v": 0
            },
            {
                "_id": "64933b83883a61d55e0b9921",
                "eip": "6239",
                "fromStatus": "unknown",
                "toStatus": "Draft",
                "title": "Semantic Soulbound Tokens",
                "status": "Draft",
                "author": "Jessica Chang (@JessicaChg)",
                "created": "2022-12-29T18:30:00.000Z",
                "changeDate": "2023-05-28T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/eip-6239-semantic-soulbound-tokens/12334",
                "deadline": "undefined",
                "requires": "165, 721, 5192",
                "changedDay": 29,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 12,
                "createdYear": 2022,
                "__v": 0
            },
            {
                "_id": "64933bb8883a61d55e0b99fe",
                "eip": "6551",
                "fromStatus": "unknown",
                "toStatus": "Draft",
                "title": "Non-fungible Token Bound Accounts",
                "status": "Draft",
                "author": "Jayden Windle (@jaydenwindle), Benny Giang <bg@futureprimitive.xyz>, Steve Jang, Druzy Downs (@druzydowns), Raymond Huynh (@huynhr), Alanah Lam <alanah@futureprimitive.xyz>, Wilkins Chung (@wwhchung) <wilkins@manifold.xyz>, Paul Sullivan (@sullivph) <paul.sullivan@manifold.xyz>",
                "created": "2023-02-22T18:30:00.000Z",
                "changeDate": "2023-05-14T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/non-fungible-token-bound-accounts/13030",
                "deadline": "undefined",
                "requires": "155, 165, 721, 1167, 1271",
                "changedDay": 15,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 2,
                "createdYear": 2023,
                "__v": 0
            },
            {
                "_id": "64933bcd883a61d55e0b9a58",
                "eip": "6786",
                "fromStatus": "unknown",
                "toStatus": "Draft",
                "title": "Registry for royalties payment for NFTs",
                "status": "Draft",
                "author": "Otniel Nicola (@OT-kthd), Bogdan Popa (@BogdanKTHD)",
                "created": "2023-03-26T18:30:00.000Z",
                "changeDate": "2023-05-18T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/eip-6786-royalty-debt-registry/13569",
                "deadline": "undefined",
                "requires": "165, 2981",
                "changedDay": 19,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 3,
                "createdYear": 2023,
                "__v": 0
            },
            {
                "_id": "64933bce883a61d55e0b9a5c",
                "eip": "6787",
                "fromStatus": "unknown",
                "toStatus": "Draft",
                "title": "Order Book DEX with Two Phase Withdrawal",
                "status": "Draft",
                "author": "Jessica (@qizheng09), Roy (@royshang), Jun (@SniperUsopp)",
                "created": "2023-03-26T18:30:00.000Z",
                "changeDate": "2023-05-22T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/order-book-dex-standard/13573",
                "deadline": "undefined",
                "requires": "undefined",
                "changedDay": 23,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 3,
                "createdYear": 2023,
                "__v": 0
            },
            {
                "_id": "64933bd0883a61d55e0b9a68",
                "eip": "6808",
                "fromStatus": "unknown",
                "toStatus": "Draft",
                "title": "Fungible Key Bound Token",
                "status": "Draft",
                "author": "Mihai Onila (@MihaiORO), Nick Zeman (@NickZCZ), Narcis Cotaie (@NarcisCRO)",
                "created": "2023-03-30T18:30:00.000Z",
                "changeDate": "2023-05-01T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/fungible-key-bound-token-kbt/13624",
                "deadline": "undefined",
                "requires": "20",
                "changedDay": 2,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 3,
                "createdYear": 2023,
                "__v": 0
            },
            {
                "_id": "64933bd2883a61d55e0b9a6f",
                "eip": "6809",
                "fromStatus": "unknown",
                "toStatus": "Draft",
                "title": "Non-Fungible Key Bound Token",
                "status": "Draft",
                "author": "Mihai Onila (@MihaiORO), Nick Zeman (@NickZCZ), Narcis Cotaie (@NarcisCRO)",
                "created": "2023-03-30T18:30:00.000Z",
                "changeDate": "2023-05-01T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/non-fungible-key-bound-token-kbt/13625",
                "deadline": "undefined",
                "requires": "721",
                "changedDay": 2,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 3,
                "createdYear": 2023,
                "__v": 0
            },
            {
                "_id": "64933bdb883a61d55e0b9a97",
                "eip": "6811",
                "fromStatus": "unknown",
                "toStatus": "Draft",
                "title": "To The Moon—10 Minute Blocks",
                "status": "Draft",
                "author": "Pandapip1 (@Pandapip1)",
                "created": "2023-03-31T18:30:00.000Z",
                "changeDate": "2023-05-10T18:30:00.000Z",
                "type": "Standards Track",
                "category": "Core",
                "discussion": "https://ethereum-magicians.org/t/ethereum-to-the-moon/13633",
                "deadline": "undefined",
                "requires": "undefined",
                "changedDay": 11,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 4,
                "createdYear": 2023,
                "__v": 0
            },
            {
                "_id": "64933bdc883a61d55e0b9a9b",
                "eip": "6821",
                "fromStatus": "unknown",
                "toStatus": "Draft",
                "title": "Support ENS Name for Web3 URL",
                "status": "Draft",
                "author": "Qi Zhou (@qizhou), Qiang Zhu (@qzhodl)",
                "created": "2023-04-01T18:30:00.000Z",
                "changeDate": "2023-05-03T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/eip-6821-support-ens-name-for-web3-url/13654",
                "deadline": "undefined",
                "requires": "137, 634, 3770, 4804",
                "changedDay": 4,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 4,
                "createdYear": 2023,
                "__v": 0
            },
            {
                "_id": "64933bdd883a61d55e0b9a9f",
                "eip": "6823",
                "fromStatus": "unknown",
                "toStatus": "Draft",
                "title": "Token Mapping Slot Retrieval Extension",
                "status": "Draft",
                "author": "qdqd (@qd-qd) <qdqdqdqdqd@protonmail.com>",
                "created": "2023-03-28T18:30:00.000Z",
                "changeDate": "2023-05-28T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/eip-6823-token-mapping-slot-retrieval-extension/13666",
                "deadline": "undefined",
                "requires": "20, 721, 1155",
                "changedDay": 29,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 3,
                "createdYear": 2023,
                "__v": 0
            },
            {
                "_id": "64933bdf883a61d55e0b9aa7",
                "eip": "6865",
                "fromStatus": "unknown",
                "toStatus": "Draft",
                "title": "On-Chain EIP-712 Visualization",
                "status": "Draft",
                "author": "Abderrahmen Hanafi (@a6-dou)",
                "created": "2023-04-09T18:30:00.000Z",
                "changeDate": "2023-05-18T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/eip-6865-on-chain-eip-712-visualization/13800",
                "deadline": "undefined",
                "requires": "712",
                "changedDay": 19,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 4,
                "createdYear": 2023,
                "__v": 0
            },
            {
                "_id": "64933be0883a61d55e0b9aab",
                "eip": "6888",
                "fromStatus": "unknown",
                "toStatus": "Draft",
                "title": "Math checking in EVM",
                "status": "Draft",
                "author": "Renan Rodrigues de Souza (@RenanSouza2)",
                "created": "2023-04-15T18:30:00.000Z",
                "changeDate": "2023-05-14T18:30:00.000Z",
                "type": "Standards Track",
                "category": "Core",
                "discussion": "https://ethereum-magicians.org/t/eip-math-checking/13846",
                "deadline": "undefined",
                "requires": "undefined",
                "changedDay": 15,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 4,
                "createdYear": 2023,
                "__v": 0
            },
            {
                "_id": "64933be4883a61d55e0b9ac2",
                "eip": "6913",
                "fromStatus": "unknown",
                "toStatus": "Draft",
                "title": "SETCODE instruction",
                "status": "Draft",
                "author": "William Morriss (@wjmelements)",
                "created": "2023-04-19T18:30:00.000Z",
                "changeDate": "2023-05-25T18:30:00.000Z",
                "type": "Standards Track",
                "category": "Core",
                "discussion": "https://ethereum-magicians.org/t/eip-6913-setcode-instruction/13898",
                "deadline": "undefined",
                "requires": "undefined",
                "changedDay": 26,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 4,
                "createdYear": 2023,
                "__v": 0
            },
            {
                "_id": "64933be6883a61d55e0b9ac9",
                "eip": "6944",
                "fromStatus": "unknown",
                "toStatus": "Draft",
                "title": "ERC-5219 Resolve Mode",
                "status": "Draft",
                "author": "Gavin John (@Pandapip1), Qi Zhou (@qizhou)",
                "created": "2023-04-26T18:30:00.000Z",
                "changeDate": "2023-05-28T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/erc-5219-resolve-mode/14088",
                "deadline": "undefined",
                "requires": "4804, 5219",
                "changedDay": 29,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 4,
                "createdYear": 2023,
                "__v": 0
            },
            {
                "_id": "64933bed883a61d55e0b9ade",
                "eip": "6953",
                "fromStatus": "unknown",
                "toStatus": "Draft",
                "title": "Network Upgrade Activation Triggers",
                "status": "Draft",
                "author": "Tim Beiko (@timbeiko)",
                "created": "2023-04-27T18:30:00.000Z",
                "changeDate": "2023-04-30T18:30:00.000Z",
                "type": "Informational",
                "category": "undefined",
                "discussion": "https://ethereum-magicians.org/t/eip-6666-network-upgrade-activation-triggers/14047",
                "deadline": "undefined",
                "requires": "2982, 3675, 6122",
                "changedDay": 1,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 4,
                "createdYear": 2023,
                "__v": 0
            },
            {
                "_id": "64933bef883a61d55e0b9ae5",
                "eip": "6956",
                "fromStatus": "unknown",
                "toStatus": "Draft",
                "title": "Asset-bound Non-Fungible Tokens",
                "status": "Draft",
                "author": "Thomas Bergmueller (@tbergmueller), Lukas Meyer (@ibex-technology)",
                "created": "2023-04-28T18:30:00.000Z",
                "changeDate": "2023-05-19T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/erc-6956-asset-bound-non-fungible-tokens/14056",
                "deadline": "undefined",
                "requires": "165, 721",
                "changedDay": 20,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 4,
                "createdYear": 2023,
                "__v": 0
            },
            {
                "_id": "64933bf6883a61d55e0b9b00",
                "eip": "6981",
                "fromStatus": "unknown",
                "toStatus": "Draft",
                "title": "Reserved Ownership Accounts",
                "status": "Draft",
                "author": "Paul Sullivan (@sullivph) <paul.sullivan@manifold.xyz>, Wilkins Chung (@wwchung) <wilkins@manifold.xyz>, Kartik Patel (@Slokh) <kartik@manifold.xyz>",
                "created": "2023-04-24T18:30:00.000Z",
                "changeDate": "2023-05-28T18:30:00.000Z",
                "type": "Standards Track",
                "category": "ERC",
                "discussion": "https://ethereum-magicians.org/t/erc-6981-reserved-ownership-accounts/14118",
                "deadline": "undefined",
                "requires": "1167, 1271",
                "changedDay": 29,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 4,
                "createdYear": 2023,
                "__v": 0
            },
            {
                "_id": "64933bf7883a61d55e0b9b08",
                "eip": "6988",
                "fromStatus": "unknown",
                "toStatus": "Draft",
                "title": "Elected block proposer has not been slashed",
                "status": "Draft",
                "author": "Mikhail Kalinin (@mkalinin)",
                "created": "2023-05-03T18:30:00.000Z",
                "changeDate": "2023-05-28T18:30:00.000Z",
                "type": "Standards Track",
                "category": "Core",
                "discussion": "https://ethereum-magicians.org/t/eip-6988-elected-block-proposer-has-not-been-slashed/14349",
                "deadline": "undefined",
                "requires": "undefined",
                "changedDay": 29,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 5,
                "createdYear": 2023,
                "__v": 0
            },
            {
                "_id": "64933bfc883a61d55e0b9b1e",
                "eip": "7045",
                "fromStatus": "unknown",
                "toStatus": "Draft",
                "title": "Increase max attestation inclusion slot",
                "status": "Draft",
                "author": "Danny Ryan (@djrtwo)",
                "created": "2023-05-17T18:30:00.000Z",
                "changeDate": "2023-05-28T18:30:00.000Z",
                "type": "Standards Track",
                "category": "Core",
                "discussion": "https://ethereum-magicians.org/t/eip-7045-increase-attestation-slot-inclusion-range/14342",
                "deadline": "undefined",
                "requires": "undefined",
                "changedDay": 29,
                "changedMonth": 5,
                "changedYear": 2023,
                "createdMonth": 5,
                "createdYear": 2023,
                "__v": 0
            }
        ]
    }
]